sensors:
    serial-number: 448438
    temperature-polling-ms: 10000
    
spring:
    datasource:
      url: jdbc:mysql://localhost/sensors
      username: sensors
      password: sensors
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      show-sql: true
    