sensors:
    serial-number: 448438
    temperature-polling-ms: 10000
    temperature-alert-polling-ms: 60000
    temperature-alert-average-duration-min: 1
    alert-delay-before-new-alert-min: 60
    temperature-alert-email-address: 
    email-address: 
    email-password: 
    
spring:
    datasource:
      url: jdbc:mysql://localhost/sensors
      username: sensors
      password: sensors
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      show-sql: true
    